try:
    # Prefer the static file generated by setuptools_scm at build time.
    # `ncatbot/_version.py` will be written by setuptools_scm when building/releases.
    from ._version import __version__  # type: ignore
except Exception:
    # Fallback for editable installs / local development where _version.py may not exist.
    __version__ = "0+unknown"

# 核心导出
from .core import BotClient, EventBus, NcatBotEvent, EventType

__all__ = [
    "__version__",
    "BotClient",
    "EventBus",
    "NcatBotEvent",
    "EventType",
]
