"""
类型存根文件 - SupportAPI

此文件由 dev/tools/generate_sync_stubs.py 自动生成。
请勿手动编辑。
"""

from typing import List, Optional, Union, Literal
from ncatbot.core.api.client import IAPIClient
from ncatbot.service import ServiceManager

# 前向声明
class AICharacterList: ...

class SupportAPI:
    """
    SupportAPI 类型存根

    包含异步方法和动态生成的同步方法（*_sync）。
    """

    # 属性声明
    _client: IAPIClient
    _service_manager: Optional[ServiceManager]

    def __init__(
        self, client: IAPIClient, service_manager: Optional[ServiceManager] = ...
    ) -> None: ...
    async def bot_exit(self) -> None: ...
    def bot_exit_sync(self) -> None: ...
    async def can_send_image(self) -> bool: ...
    def can_send_image_sync(self) -> bool: ...
    async def can_send_record(self, group_id: Union[str, int]) -> bool: ...
    def can_send_record_sync(self, group_id: Union[str, int]) -> bool: ...
    async def get_ai_characters(
        self, group_id: Union[str, int], chat_type: Literal[1, 2]
    ) -> "AICharacterList": ...
    def get_ai_characters_sync(
        self, group_id: Union[str, int], chat_type: Literal[1, 2]
    ) -> "AICharacterList": ...
    async def get_ai_record(
        self, group_id: Union[str, int], character_id: str, text: str
    ) -> str: ...
    def get_ai_record_sync(
        self, group_id: Union[str, int], character_id: str, text: str
    ) -> str: ...
    async def get_version_info(self) -> dict: ...
    def get_version_info_sync(self) -> dict: ...
    async def ocr_image(self, image: str) -> List[dict]: ...
    def ocr_image_sync(self, image: str) -> List[dict]: ...
