"""
类型存根文件 - AccountAPI

此文件由 dev/tools/generate_sync_stubs.py 自动生成。
请勿手动编辑。
"""

from typing import Any, Dict, List, Optional, Union, Literal
from ncatbot.core.api.client import IAPIClient
from ncatbot.service import ServiceManager

# 前向声明
class CustomFaceList: ...
class LoginInfo: ...

class AccountAPI:
    """
    AccountAPI 类型存根

    包含异步方法和动态生成的同步方法（*_sync）。
    """

    # 属性声明
    _client: IAPIClient
    _service_manager: Optional[ServiceManager]

    def __init__(
        self, client: IAPIClient, service_manager: Optional[ServiceManager] = ...
    ) -> None: ...
    async def AskShareGroup(self, group_id: Union[str, int]) -> None: ...
    def AskShareGroup_sync(self, group_id: Union[str, int]) -> None: ...
    async def ask_share_group(self, group_id: Union[str, int]) -> None: ...
    def ask_share_group_sync(self, group_id: Union[str, int]) -> None: ...
    async def create_collection(self, raw_data: str, brief: str) -> None: ...
    def create_collection_sync(self, raw_data: str, brief: str) -> None: ...
    async def delete_friend(
        self, user_id: Union[str, int], block: bool = ..., both: bool = ...
    ) -> None: ...
    def delete_friend_sync(
        self, user_id: Union[str, int], block: bool = ..., both: bool = ...
    ) -> None: ...
    async def fetch_custom_face(self, count: int = ...) -> "CustomFaceList": ...
    def fetch_custom_face_sync(self, count: int = ...) -> "CustomFaceList": ...
    async def get_friend_list(self) -> List[dict]: ...
    def get_friend_list_sync(self) -> List[dict]: ...
    async def get_friends_with_cat(self) -> List[dict]: ...
    def get_friends_with_cat_sync(self) -> List[dict]: ...
    async def get_login_info(self) -> "LoginInfo": ...
    def get_login_info_sync(self) -> "LoginInfo": ...
    async def get_recent_contact(self) -> List[dict]: ...
    def get_recent_contact_sync(self) -> List[dict]: ...
    async def get_status(self) -> dict: ...
    def get_status_sync(self) -> dict: ...
    async def get_stranger_info(self, user_id: Union[str, int]) -> dict: ...
    def get_stranger_info_sync(self, user_id: Union[str, int]) -> dict: ...
    async def mark_group_msg_as_read(self, group_id: Union[str, int]) -> None: ...
    def mark_group_msg_as_read_sync(self, group_id: Union[str, int]) -> None: ...
    async def mark_private_msg_as_read(self, user_id: Union[str, int]) -> None: ...
    def mark_private_msg_as_read_sync(self, user_id: Union[str, int]) -> None: ...
    async def nc_get_user_status(self, user_id: Union[str, int]) -> dict: ...
    def nc_get_user_status_sync(self, user_id: Union[str, int]) -> dict: ...
    async def send_like(
        self, user_id: Union[str, int], times: int = ...
    ) -> Dict[str, Any]: ...
    def send_like_sync(
        self, user_id: Union[str, int], times: int = ...
    ) -> Dict[str, Any]: ...
    async def set_friend_add_request(
        self, flag: str, approve: bool, remark: Optional[str] = ...
    ) -> None: ...
    def set_friend_add_request_sync(
        self, flag: str, approve: bool, remark: Optional[str] = ...
    ) -> None: ...
    async def set_friend_remark(
        self, user_id: Union[str, int], remark: str
    ) -> None: ...
    def set_friend_remark_sync(self, user_id: Union[str, int], remark: str) -> None: ...
    async def set_online_status(
        self, status: int, ext_status: int, battery_status: int
    ) -> None: ...
    def set_online_status_sync(
        self, status: int, ext_status: int, battery_status: int
    ) -> None: ...
    async def set_qq_avatar(self, file: str) -> None: ...
    def set_qq_avatar_sync(self, file: str) -> None: ...
    async def set_qq_profile(
        self, nickname: str, personal_note: str, sex: Literal["未知", "男", "女"]
    ) -> None: ...
    def set_qq_profile_sync(
        self, nickname: str, personal_note: str, sex: Literal["未知", "男", "女"]
    ) -> None: ...
    async def set_self_longnick(self, long_nick: str) -> None: ...
    def set_self_longnick_sync(self, long_nick: str) -> None: ...
